apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tsmc-nycu-lab-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: quay.io/tsmc-nycu-lab-13/backend
        name: backend
        envFrom:
          - secretRef:
              name: backend-env
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256M"
            cpu: "500m"
      #   volumeMounts:
      #   - name: env
      #     mountPath: "/backend/.env"
      #     subPath: .env
      #     readOnly: true
      # volumes:
      # - name: env
      #   secret:
      #     secretName: backend-env